"""foreign key add to book table

Revision ID: 276f4d33bc82
Revises: 6fc2b1ebb5d4
Create Date: 2025-03-25 18:10:59.621493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '276f4d33bc82'
down_revision: Union[str, None] = '6fc2b1ebb5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastBooks', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'fastBooks', 'users', ['user_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fastBooks', type_='foreignkey')
    op.drop_column('fastBooks', 'user_uid')
    # ### end Alembic commands ###
